name: atomic_flutter
description: A lightweight, reactive state management solution for Flutter applications with async state support and domain-specific atoms.
version: 0.2.1
homepage: https://github.com/arkarmintun1/atomic_flutter

environment:
  sdk: ^3.6.2
  flutter: '>=1.17.0'

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# Additional package metadata
repository: https://github.com/arkarmintun1/atomic_flutter
issue_tracker: https://github.com/arkarmintun1/atomic_flutter/issues
documentation: https://github.com/arkarmintun1/atomic_flutter#readme

funding:
  - https://github.com/sponsors/arkarmintun1

topics:
  - state-management
  - reactive
  - flutter
  - atoms
  - async
